### ISSUE TITLE
xunit 2.9 compatability

### ISSUE THREAD

**Issue by channell** [asherber/Xunit.Priority#10]
in my tests, xunit ignored the priority attribute.. might be my test case, or an xunit change.. might be worth checking

**Comment by asherber** [comment]
The unit tests for this library pass using xunit 2.9.0.

Do you have an example of code that doesn't work? Is your class decorated with the `TestCaseOrder` attribute, as indicated in the [readme](https://github.com/asherber/Xunit.Priority?tab=readme-ov-file#usage)?

**Comment by channell** [comment]
Yes, thanks.  I think the case was a fragile assumption in my [testcases](
https://github.com/channell/Hiperspace/blob/66be523ab1e60ac70de6ddb56bb1065bb662c84e/examples/Invoice/UnitTest1.cs#L170)

I'd assumed that each test would be run in the same environment, which may not  be the case.
