### ISSUE TITLE
async test methods

### ISSUE THREAD

**Issue by aandrieiev1998** [asherber/Xunit.Priority#8]
For async test methods ordering doesn't work? It is required to disable parallelization for that. Is there a way to achieve that?

**Comment by asherber** [comment]
Can you provide a simple class where ordering doesn't work for you?

**Comment by aandrieiev1998** [comment]
`
using Xunit;
using Xunit.Abstractions;
using Xunit.Priority;

namespace SearchApiTests.TestImpl;

[TestCaseOrderer(PriorityOrderer.Name, PriorityOrderer.Assembly)]
public class MyAwesomeTest : TestBase, IClassFixture<MyAwesomeFixture>
{
    private readonly MyAwesomeFixture _fixture;

    public MyAwesomeTest(MyAwesomeFixture fixture, ITestOutputHelper output) : base(output)
    {
        _fixture = fixture;
    }

    [Fact, Priority(1)]
    public async Task CreateTypeRegistryTest()
    {
        // Act
        
    }

    [Fact, Priority(2)]
    public async Task CreateInformationModelTest()
    {
        // Act
        
    }

    [Fact, Priority(3)]
    public async Task InsertTimescaleTest()
    {
        // Act
        
    }
}
`

**Comment by aandrieiev1998** [comment]
Raw example:

```
using Xunit;
using Xunit.Priority;

public class Testorder
{
    [Fact, Priority(1)]
    public async Task Test1()
    {
        Assert.True(true);
    }
    
    [Fact, Priority(2)]
    public async Task Test2()
    {
        Assert.True(true);
    }
    
    [Fact, Priority(3)]
    public async Task Test3()
    {
        Assert.True(true);
    }
    
    [Fact, Priority(4)]
    public async Task Test4()
    {
        Assert.True(true);
    }
}
```

**Comment by asherber** [comment]
You need to apply the orderer to the class:

```csharp
using Xunit;
using Xunit.Priority;

[TestCaseOrderer(PriorityOrderer.Name, PriorityOrderer.Assembly)]
public class Testorder
{

}
